### ISSUE TITLE
ER_NO_DEFAULT_FOR_FIELD thrown when calling createBackInStockSubscription()

### ISSUE THREAD

**Issue by is0utfitters** [calliT-today/vendure-plugin-back-in-stock#1]
Calling createBackInStockSubscription with a valid customer email address in the ShopAPI Playground produces the following Vendure Error:
```
[server] error 4/14/23, 10:54 AM - [Vendure Server] ER_NO_DEFAULT_FOR_FIELD: Field 'email' doesn't have a default value
[server] QueryFailedError: ER_NO_DEFAULT_FOR_FIELD: Field 'email' doesn't have a default value
```
Environment: MySQL 5.7.39, Vendure 1.9.5, Node v18.10

**Comment by prasmalla** [comment]
#https://github.com/vendure-ecommerce/vendure/issues/2099
